### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [phisith/nimble-technical-test#4]
Hello Phisit 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need additional time, please let us know as soon as possible so we can plan accordingly.

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now wrapped up the first round of reviews. I have focused on the main areas of improvement (there are more, especially in terms of code organization and resting) to ensure the code review process can be wrapped up within 2-3 days.

I am looking forward to your feedback on the open issues.

**Comment by phisith** [comment]
Hi Mr.Olivier, Thank you for reviewing my code, I will try to fix and respond to each issue asap.

**Comment by olivierobert** [comment]
@phisith I have reviewed all your feedback and fixes. You were very fast 👏 As a result, we can now wrap up this stage of the recruitment process. Our team will be in touch with you by email shortly. 

Thank you for your efforts so far!
