### ISSUE TITLE
[Bug] Setting up the application fails

### ISSUE THREAD

**Issue by olivierobert** [phisith/nimble-technical-test#5]
## Issue

While the README is very detailed (kudos for your effort), the application cannot be set up locally by following the instructions. 

The Docker containers are running correctly:

![image](https://user-images.githubusercontent.com/696529/223322862-9f0d04d5-46c6-4732-8cd7-293b20cdd9e8.png)

However, the installation fails at the database migration step:

![image](https://user-images.githubusercontent.com/696529/223322947-ca2a4448-613f-4ba1-81ed-19c23e8d1987.png)

## Expected

Following the README should be sufficient to set up the applications in a local environment.

> **Warning**
> Some environment variables seem to rely on your local machine directories 🙈 
> https://github.com/phisith/nimble-technical-test/blob/3def9d95906a8d95fca442ee15712d9acf1c7375/.env#L4

> **Note**
> A Makefile could be used to simplify the setup steps 
> See an example in our team template: https://github.com/nimblehq/rails-templates/blob/develop/Makefile

**Comment by phisith** [comment]
Hi Mr. Olivier, Thank you for giving the note to improve my project setup.

I implemented Makefile into this project, fix bugs the database bugs, and also updated the Readme file.

Thank you.
